/*
	actionType 出入口
*/

// 请求状态
const Status = {
	FETCHING: 'FETCHING',
	DONE: 'DONE',
	FAILED: 'FAILED',
}

// 博客
const Blog = {
  REQUEST_FETCH: 'REQUEST_FETCH_BLOG',
  RECEIVE_FETCH: 'RECEIVE_FETCH_BLOG',
  FAILED_FETCH: 'FAILED_FETCH_BLOG',
  UPDATE_PAGE_INFO: 'UPDATE_PAGE_INFO_BLOG',
  CHANGE_PAGE: 'CHANGE_PAGE_BLOG',
}

// 站点信息
const Site = {
  RECEIVE_FETCH_SUMMATION: 'RECEIVE_FETCH_SUMMATION',

  OPEN_SUBSCRIBE: 'OPEN_SUBSCRIBE',
  CLOSE_SUBSCRIBE: 'CLOSE_SUBSCRIBE',

  REQUEST_SUBSCRIBE: 'REQUEST_SUBSCRIBE_SUBMODAL',
  RECEIVE_SUBSCRIBE: 'RECEIVE_SUBSCRIBE_SUBMODAL',
  FAILED_SUBSCRIBE: 'FAILED_SUBSCRIBE_SUBMODAL',

}

const Comment = {

  BOARD_FETCH_REQUEST: 'BOARD_FETCH_REQUEST_COMMENT',
  BOARD_FETCH_RECEIVE: 'BOARD_FETCH_RECEIVE_COMMENT',
  BOARD_FETCH_FAIELD: 'BOARD_FETCH_FAIELD_COMMENT',
  BOARD_MORE_REQUEST: 'BOARD_MORE_REQUEST_COMMENT',
  BOARD_MORE_RECEIVE: 'BOARD_MORE_RECEIVE_COMMENT',
  BOARD_MORE_FAIELD: 'BOARD_MORE_FAIELD_COMMENT',
  BOARD_ADD_REQUEST: 'BOARD_ADD_REQUEST_COMMENT',
  BOARD_ADD_RECEIVE: 'BOARD_ADD_RECEIVE_COMMENT',
  BOARD_ADD_FAIELD: 'BOARD_ADD_FAIELD_COMMENT',


}

export {
	Status,
	Blog,
	Site,
}